# data/tracks

pkgdatadir= $(datadir)/games/$(PACKAGE)/data/tracks
nobase_dist_pkgdata_DATA = $(shell find $(srcdir) -name "*.jpg")           \
                           $(shell find $(srcdir) -name "*.JPG")           \
                           $(shell find $(srcdir) -name "*.png")           \
                           $(shell find $(srcdir) -name "*.b3d")           \
                           $(shell find $(srcdir) -name "License.txt")     \
                           $(shell find $(srcdir) -name "*.xml")           \
                           $(shell find $(srcdir) -name "*.challenge")     \
                           $(shell find $(srcdir) -name "Music_license.rtf") \
                           $(shell find $(srcdir) -name "*.music")         \
                           b3d_export.py stk_track.py stk_browser.py       \
                           $(shell find $(srcdir) -name "*.ogg")

